version: '3.3'

services:
  calend:
    build: .
    container_name: app-calend
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:15
    container_name: postgres-calend
    environment:
      POSTGRES_PASSWORD: passw0rd
      PG_PASSWORD: passw0rd
      POSTGRES_DB: server_db
    ports:
      - "15000:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -p 5432" ]
      interval: 10s
      timeout: 5s
      retries: 5

  elastic:
    container_name: elastic-calend
    image: elasticsearch:7.17.2
    environment:
      - cluster.name=calend
      - discovery.type=single-node
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
      - logger.level=ERROR
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "15001:9200"
      - "15002:9300"
