version: '3.3'

services:
  postgres:
    image: postgres:13
    container_name: postgres-calend
    environment:
      POSTGRES_PASSWORD: passw0rd
      PG_PASSWORD: passw0rd
      POSTGRES_DB: server_db
    ports:
      - "5432:5432"