// Code generated by ent, DO NOT EDIT.

package ent

import (
	"calend/internal/modules/db/ent/accessright"
	"fmt"
	"strings"

	"entgo.io/ent/dialect/sql"
)

// AccessRight is the model entity for the AccessRight schema.
type AccessRight struct {
	config
	// ID of the ent.
	ID int `json:"id,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AccessRight) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case accessright.FieldID:
			values[i] = new(sql.NullInt64)
		default:
			return nil, fmt.Errorf("unexpected column %q for type AccessRight", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AccessRight fields.
func (ar *AccessRight) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case accessright.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			ar.ID = int(value.Int64)
		}
	}
	return nil
}

// Update returns a builder for updating this AccessRight.
// Note that you need to call AccessRight.Unwrap() before calling this method if this AccessRight
// was returned from a transaction, and the transaction was committed or rolled back.
func (ar *AccessRight) Update() *AccessRightUpdateOne {
	return NewAccessRightClient(ar.config).UpdateOne(ar)
}

// Unwrap unwraps the AccessRight entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ar *AccessRight) Unwrap() *AccessRight {
	_tx, ok := ar.config.driver.(*txDriver)
	if !ok {
		panic("ent: AccessRight is not a transactional entity")
	}
	ar.config.driver = _tx.drv
	return ar
}

// String implements the fmt.Stringer.
func (ar *AccessRight) String() string {
	var builder strings.Builder
	builder.WriteString("AccessRight(")
	builder.WriteString(fmt.Sprintf("id=%v", ar.ID))
	builder.WriteByte(')')
	return builder.String()
}

// AccessRights is a parsable slice of AccessRight.
type AccessRights []*AccessRight
