// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AccessRight is the predicate function for accessright builders.
type AccessRight func(*sql.Selector)

// Event is the predicate function for event builders.
type Event func(*sql.Selector)

// Invitation is the predicate function for invitation builders.
type Invitation func(*sql.Selector)

// Tag is the predicate function for tag builders.
type Tag func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
