// Code generated by MockGen. DO NOT EDIT.
// Source: calend/internal/modules/domain/event/service (interfaces: IInvitationRepo)

// Package service is a generated GoMock package.
package service

import (
	dto "calend/internal/modules/domain/event/dto"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIInvitationRepo is a mock of IInvitationRepo interface.
type MockIInvitationRepo struct {
	ctrl     *gomock.Controller
	recorder *MockIInvitationRepoMockRecorder
}

// MockIInvitationRepoMockRecorder is the mock recorder for MockIInvitationRepo.
type MockIInvitationRepoMockRecorder struct {
	mock *MockIInvitationRepo
}

// NewMockIInvitationRepo creates a new mock instance.
func NewMockIInvitationRepo(ctrl *gomock.Controller) *MockIInvitationRepo {
	mock := &MockIInvitationRepo{ctrl: ctrl}
	mock.recorder = &MockIInvitationRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIInvitationRepo) EXPECT() *MockIInvitationRepoMockRecorder {
	return m.recorder
}

// CreateBulk mocks base method.
func (m *MockIInvitationRepo) CreateBulk(arg0 context.Context, arg1 dto.CreateInvitations) (dto.Invitations, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBulk", arg0, arg1)
	ret0, _ := ret[0].(dto.Invitations)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateBulk indicates an expected call of CreateBulk.
func (mr *MockIInvitationRepoMockRecorder) CreateBulk(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBulk", reflect.TypeOf((*MockIInvitationRepo)(nil).CreateBulk), arg0, arg1)
}

// DeleteByEventUuid mocks base method.
func (m *MockIInvitationRepo) DeleteByEventUuid(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByEventUuid", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByEventUuid indicates an expected call of DeleteByEventUuid.
func (mr *MockIInvitationRepoMockRecorder) DeleteByEventUuid(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByEventUuid", reflect.TypeOf((*MockIInvitationRepo)(nil).DeleteByEventUuid), arg0, arg1)
}
