// Code generated by ent, DO NOT EDIT.

package accessright

const (
	// Label holds the string label denoting the accessright type in the database.
	Label = "access_right"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// Table holds the table name of the accessright in the database.
	Table = "access_rights"
)

// Columns holds all SQL columns for accessright fields.
var Columns = []string{
	FieldID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
