package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.29

import (
	"calend/internal/models/access"
	"calend/internal/modules/domain/access_right/dto"
	"context"
)

// AccessRight is the resolver for the AccessRight field.
func (r *queryResolver) AccessRight(ctx context.Context, code access.Type) (*dto.AccessRight, error) {
	ar, err := r.arService.GetByCode(ctx, code)
	if err != nil {
		return nil, err
	}

	return ar, nil
}

// AccessRights is the resolver for the AccessRights field.
func (r *queryResolver) AccessRights(ctx context.Context) ([]*dto.AccessRight, error) {
	ar, err := r.arService.List(ctx)
	if err != nil {
		return nil, err
	}

	return ar, nil
}
