package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.29

import (
	"calend/internal/modules/domain/auth/dto"
	dto1 "calend/internal/modules/domain/user/dto"
	"context"
)

// SingUp is the resolver for the SingUp field.
func (r *mutationResolver) SingUp(ctx context.Context, newUser dto.NewUser) (*dto1.User, error) {
	user, err := r.authService.SignUp(ctx, &newUser)

	return user, err
}
