package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.29

import (
	"calend/internal/modules/domain/auth/dto"
	"context"
)

// Login is the resolver for the Login field.
func (r *queryResolver) Login(ctx context.Context, credentials dto.UserCredentials) (*dto.JWT, error) {
	jwt, err := r.authService.Login(ctx, &credentials)

	return jwt, err
}
