package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.29

import (
	"calend/internal/modules/domain/auth/dto"
	dto1 "calend/internal/modules/domain/user/dto"
	"context"
)

// SingUp is the resolver for the SingUp field.
func (r *mutationResolver) SingUp(ctx context.Context, newUser dto.NewUser) (*dto1.User, error) {
	user, err := r.authService.SignUp(ctx, &newUser)

	return user, err
}

// Login is the resolver for the Login field.
func (r *queryResolver) Login(ctx context.Context, credentials dto.UserCredentials) (*dto.JWT, error) {
	jwt, err := r.authService.Login(ctx, &credentials)

	return jwt, err
}

// RefreshToken is the resolver for the RefreshToken field.
func (r *queryResolver) RefreshToken(ctx context.Context, refreshToken string) (*dto.Tokens, error) {
	tokens, err := r.authService.RefreshAccessToken(ctx, refreshToken)

	return tokens, err
}
