package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.29

import (
	"calend/internal/models/session"
	"calend/internal/modules/domain/user/dto"
	"calend/internal/modules/graphql/generated"
	"context"
)

// User is the resolver for the User field.
func (r *sessionResolver) User(ctx context.Context, obj *session.Session) (*dto.User, error) {
	user, err := r.userService.GetByUuid(ctx, obj.UserUuid)

	return user, err
}

// Session returns generated.SessionResolver implementation.
func (r *Resolver) Session() generated.SessionResolver { return &sessionResolver{r} }

type sessionResolver struct{ *Resolver }
