package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.29

import (
	"context"
	"fmt"
)

// GenerateData is the resolver for the GenerateData field.
func (r *mutationResolver) GenerateData(ctx context.Context) (*string, error) {
	panic(fmt.Errorf("not implemented: GenerateData - GenerateData"))
}
