package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.29

import (
	"calend/internal/modules/domain/event/dto"
	search_dto "calend/internal/modules/domain/search/dto"
	"calend/internal/pkg/search/paginate"
	"context"
)

// SearchEvent is the resolver for the SearchEvent field.
func (r *queryResolver) SearchEvent(ctx context.Context, paginate paginate.ByPage, filter *search_dto.EventFilter, sort *search_dto.EventSort) ([]*dto.Event, error) {
	searchRequest := &search_dto.EventSearchRequest{
		Filter:   filter,
		Sort:     sort,
		Paginate: &paginate,
	}
	events, err := r.searchService.SearchEvents(ctx, searchRequest)
	if err != nil {
		return nil, err
	}

	return events, nil
}
